// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package myapp

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func initApp() app {
	mainDbConfig := newDBConfig()
	db := newDB(mainDbConfig)
	mainApp := NewApp(mainDbConfig, db)
	return mainApp
}
